### ISSUE TITLE
Hope there is a plugin for draw high quality labels on the image.

### ISSUE THREAD

**Issue by xin-ran-w** [voxel51/fiftyone-plugins#102]
Fiftyone is the best dataset management tool I've ever used. I have a small piece of advice on label drawing.
The APP lacks interactive tools to save the beautiful labels on the image, and it will be more convenient if this plugin is added.
I now use the API `foua.draw_labeled_image` and set the complicate config to draw labels on an image. However, the quality of the label is not very high like the view in the app, like the following figure. I hope you can consider my suggestion.
![image](https://github.com/voxel51/fiftyone-plugins/assets/87413406/56bfb494-a181-48ff-9671-9093c69aa147)

**Comment by ehofesmann** [comment]
Hey @xin-ran-w ! 

Did you know that you can right click an image in the App in FiftyOne and click "Save image as..." and it will save the image with annotations? Is that helpful?

![download](https://github.com/voxel51/fiftyone-plugins/assets/21222883/81747964-3522-43de-991f-377c6f69c7d8)

**Comment by xin-ran-w** [comment]
Thank you for your reply. Yes, I also tried this function, but the output is not just the image and label, there is some padding around the image. Each time I have to crop the image.
![image](https://github.com/voxel51/fiftyone-plugins/assets/87413406/0fdb9192-a178-4a3a-b2fe-9929a533e658)
