### ISSUE TITLE
HowTo: Custom Plugin to compute timestamps & weekdays of samples

### ISSUE THREAD

**Issue by mmoollllee** [voxel51/fiftyone-plugins#121]
Hey there :)
Thanks for the awesome work!
I'd like to create a fiftyone plugin to compute samples' timestamps, either from filename or file's metadata, to add the following filter options:

1. by timerange in general (e.g. 2023-01-23 to 2023-05-21). Could be just the unix timestamp.
2. by weekday (e.g. Mondays to Wednesdays). Could be 0 - 6.
3. by time (e.g. 8 am - 11 am). Could be 0.00 - 23.99

Usecase: I have a big dataset from construction sites and want to create a dataset from it that's made up evenly from different seasons, weekdays, daytimes,... So I need to filter by weekday for example, as I really don't need data from sundays...

Could someone helping me with the first steps and guide me a little?
Where do I start? I guess first step would be to compute a new metadata-field to give fiftyone access to the sample's timestamp?
Having this data I could compute other fields like time ( 0.00 - 23.99 ) and weekdays (0 - 6).
From there I might be able to find out the rest from browsing other plugins' repositories :)

**Comment by brimoor** [comment]
Hi @mmoollllee 👋 

Sounds like a great use case!

To get you started, every `Sample` in a FiftyOne dataset has an `id` field which is a [MongoDB ObjectId](https://www.mongodb.com/docs/manual/reference/method/ObjectId/). These ObjectId's contain a 4-byte timestamp representing when the sample was created, so you can actually already perform creation date-based queries on any FiftyOne dataset using [date-based views](https://docs.voxel51.com/user_guide/using_views.html#date-based-views).

The key is to start with this expression that will extract the creation date:

```py
from fiftyone import ViewField as F

# An expression that extracts the date portion from the sample's ID
created_at = F("_id").to_date()
```

From there, you can do things like date-based comparisons:

```py
from datetime import datetime

dt1 = datetime(...)
dt2 = datetime(...)

view = dataset.match((created_at > dt1) & (created_at < dt2))
```

FiftyOne's view expression language also contains a variety of utilities you can use to easily query based on certain parts of a date:

```py
created_at.millisecond()
created_at.second()
created_at.minute()
created_at.hour()
created_at.day_of_week()
created_at.day_of_month()
created_at.day_of_year()
created_at.week()
created_at.month()
created_at.year()
```

Check out the documentation for [ViewExpression.millisecond()](https://docs.voxel51.com/api/fiftyone.core.expressions.html#fiftyone.core.expressions.ViewExpression.millisecond
) and start scrolling down to see more information about these expressions.

Here's some examples:

```py
import fiftyone as fo
import fiftyone.zoo as foz
from fiftyone import ViewField as F

dataset = foz.load_zoo_dataset("quickstart")
created_at = F("_id").to_date()

# Extract the raw values to see what we're working with
values = dataset.values(created_at)
print(values)
# [datetime.datetime(2024, 3, 4, 14, 25, 41), datetime.datetime(2024, 3, 4, 14, 25, 41), ...]

# Compute a histogram of the second portion of each sample
print(dataset.count_values(created_at.second()))
# {42: 54, 43: 47, 41: 61, 44: 38}

view = dataset.match(created_at.second() == 42)
print(len(view))
# 54

# Date comparison queries
dt1 = values[30]
dt2 = values[170]
view = dataset.match((created_at > dt1) & (created_at < dt2))
print(len(view))
# 101  <- because timestamps are only accurate to the second level
```

**Comment by brimoor** [comment]
From here you should be able to build a pretty cool operator whose `resolve_input()` provides a variety of different input fields to accept dates, seasons, days, or other conditions you're interested in filtering on.

The `execute()` method of your operator could then construct + load the view of interest like so:

```py
import json
from bson import json_util

def execute(self, ctx):
    # Parse your parameters
    ... = ctx.params[...]

    # Build your view
    view = ctx.dataset.match(...)

    # Load view in App
    view_stages = json.loads(json_util.dumps(view._serialize()))
    ctx.trigger("set_view", params={"view": view_stages})
```

**Comment by brimoor** [comment]
You could also populate a dedicated `DateTimeField` on each of your dataset, which would allow you to perform basic `dt1 < created_at < dt2` queries using the App's builtin sidebar without building a custom plugin at all (although the plugin will be sweet, so I hope you do it!!!)

You could populate this field manually in your sample ingestion pipelines like so:

```py
sample = fo.Sample(filepath=..., created_at=datetime(...), ...)

dataset.add_samples([sample, ...])
```

Or you could retroactively populate them based on the `id` field of your existing datasets like so:

```py
# Declare field (does nothing if already exists)
dataset.add_sample_field("created_at", fo.DateTimeField)

# Samples whose created_at field is not populated
view = dataset.exists("created_at", bool=False)

# Populate created_at field based on id field
values = view.values(F("_id").to_date())
view.set_values("created_at", values)
```

**Comment by imanjra** [comment]
Hi @mmoollllee

As Brian hinted above, with resolve_input of an operator, you can provide the operator user with an option to provide a date-time and much more to build params for operator's execution. One relevant example would be rendering a date-time input which would let the user pick date and time interactively like:

```py
 def resolve_input(self, ctx):
        inputs = types.Object()

        inputs.str(
            "date",
            view=types.TextFieldView(
                componentsProps={"field": {"type": "datetime-local"}}
            ),
        )

        return types.Property(inputs) 
```

Preview of `datetime-local`:
![image](https://github.com/voxel51/fiftyone-plugins/assets/25350704/c7a0f7b4-5d43-4c8c-baf4-b3f842f3ae9e)

**Comment by mmoollllee** [comment]
Awesomee!!!! Thanks for all the input :)

I came up with the following so far:
```python
import re
from datetime import datetime

import fiftyone as fo
import fiftyone.operators as foo


def get_filepath(sample):
    return (
        sample.local_path if hasattr(sample, "local_path") else sample.filepath
    )


def timestamp_from_filepath(f):
    matches = re.search(r".*([0-9]{4})-?([0-9]{2})-?([0-9]{2})_([0-9]{2})?-?([0-9]{2})?-?([0-9]{2})?.*?", f).groups()
    matches = ['00' if i is None else i for i in matches] # Replace not found items with "01"
    return matches


def compute_timestamps_from_filepath(sample):
    year, month, day, hour, minute, second = timestamp_from_filepath(get_filepath(sample))
    string = f'{year}-{month}-{day}_{hour}-{minute}-{second}'
    dt = datetime.strptime(string, "%Y-%m-%d_%H-%M-%S")
    weekday = dt.weekday()
    time = int(hour) + (int(minute) / 60) + (int(second) / 6000)
    return dt, weekday, time


################################################################
################################################################

class ComputeTimestampsFromFilepath(foo.Operator):
    @property
    def config(self):
        return foo.OperatorConfig(
            name="compute_timestamps_from_filepath",
            label="Compute Timestamps from Filepath",
            description="Filter by various timestamp informations found in filepath"
        )


    def execute(self, ctx):
        view = ctx.view
        if view is None:
            view = ctx.dataset

        ctx.dataset.add_sample_field("datetime", fo.DateTimeField)
        ctx.dataset.add_sample_field("weekday", fo.IntField)
        ctx.dataset.add_sample_field("time", fo.FloatField)

        for sample in view.iter_samples(autosave=True, progress=True):
            dt, weekday, time = compute_timestamps_from_filepath(sample)
            sample["datetime"] = dt
            sample["weekday"] = weekday
            sample["time"] = time

    def __call__(self, sample_collection):
        ctx = dict(view=sample_collection.view())
        params = dict(target="CURRENT_VIEW")
        return foo.execute_operator(self.uri, ctx, params=params)


def register(p):
    p.register(ComputeTimestampsFromFilepath)
```
which works for my case by calling:
```python
compute_timestamps = foo.get_operator("@mmoollllee/timestamps/compute_timestamps_from_filepath")
compute_timestamps(dataset)
```

Results in:
<img width="255" alt="FiftyOne DateTime Filters" src="https://github.com/voxel51/fiftyone-plugins/assets/26859300/b05081d8-818c-4b8d-8e97-ac736d0643e5">
```

**Comment by mmoollllee** [comment]
Next I'd like to implement reading datetime from the `created_at` field to call this like so:

```python
compute_timestamps = foo.get_operator("@mmoollllee/timestamps/compute_timestamps")
compute_timestamps(dataset, source="created_at")
```

But doing something like this won't work as I'm on the wrong path:
```python
sample.get_field("_id").to_date()
```
How can I retrieve this "_id" field from sample?

**Comment by brimoor** [comment]
Looking good! 😎 

FYI, for the `execute()` method of your `compute_timestamps_from_filepath` operator, this will likely be more efficient for large datasets:

```py
dts, weekdays, times = [], [], []
for filepath in view.values("filepath"):
    dt, weekday, time = compute_timestamps_from_filepath(filepath)
    dts.append(dt)
    weekdays.append(weekday)
    times.append(time)

view.set_values("datetime", dts)
view.set_values("weekday", weekdays)
view.set_values("time", times)
```

In general using `values()` + `set_values()` to read + write specific fields will keep I/O to the absolute minimum.

You can apply the same idea for your `compute_timestamps` operator:

```py
datetimes = view.values(F("_id").to_date())
view.set_values("datetime", datetimes)
```

Or, if you want to implement it using in-memory `Sample` objects, you can retrieve the time like so:

```py
sample._id.generation_time
```
