### ISSUE TITLE
Can't do any data augmentation on my custom dataset with Albumentations

### ISSUE THREAD

**Issue by iza611** [voxel51/fiftyone-plugins#138]
I am sorry if I submitted this in a wrong place or category. I can't really find any information on this problem that I'm having and would appreciate any help. Basically, whenever I try to apply any augmentations using the Albumentations library in FiftyOne, the created images don't load at all.

Here is what I did and the outputs I got:

1. Created a custom dataset in FiftyOne and labelled it with CVAT
2. Followed this tutorial https://docs.voxel51.com/tutorials/data_augmentation.html to create 3 augmented images based on selected samples.
3. Run 'View last Albumentations run'. The output was a message: 'Failed to execute operator @voxel51/operators/set_view. See console for details.'
4. Opened the 'augmented' tag in FiftyOne. Output:
![Zrzut ekranu 2024-06-19 170952](https://github.com/voxel51/fiftyone-plugins/assets/57008248/36a60ebe-8338-4e3f-83cd-4c5ce86e1688)
6. When opened each of those displayed a message: 'This image failed to load. The file may not exist, or its type (image/jpeg) may be unsupported.'
The labels though seem to be correct, but the image doesn't load.
8. Went to the folder where the dataset is located. The size didn't change. I'd expect it to contain 3 extra images.

I tried deleting the dataset and importing it again as a fresh new one, but the problem persist.

**Comment by jacobmarks** [comment]
Hi @iza611 thanks for sharing this, would you mind sharing a few more details:

1. What versions of FiftyOne, Albumentations, and the FiftyOne Albumentations plugin you are using?
2. What the console shows when you encounter this error?

One additional note:
The augmentation images will be generated in a temporary directory, not the same directory as your dataset's images. This is because this plugin is meant for testing out augmentation strategies. Typically for training, augmentation happens on the fly. This plugin helps you to identify good combinations of transforms and hyperparams to use for that on-the-fly augmentation

**Comment by iza611** [comment]
Hi @jacobmarks, thank you for replying, here are the details:

1. FiftyOne v0.23.7, Albumentations v1.4.10, FiftyOne Albumentations plugin v1.0.10
2. When I apply transformations, the console doesn't show any errors or I might not see them because the webpage automatically refreshes right after. Then when I run the 'View last Albumentations run' command the console shows:

index.6894b23b.js:1113 
 
[{…}]
0
: 
{reason: 'Invalid object', property: Jd, path: 'view'}
length
: 
1
[[Prototype]]
: 
Array(0)
$kr	@	index.6894b23b.js:1113
await in $kr (async)		
(anonymous)	@	index.6894b23b.js:1113
await in (anonymous) (async)		
(anonymous)	@	index.6894b23b.js:318
(anonymous)	@	index.6894b23b.js:318
ube	@	index.6894b23b.js:89
D7t	@	index.6894b23b.js:318
q$e	@	index.6894b23b.js:318
(anonymous)	@	index.6894b23b.js:318
(anonymous)	@	index.6894b23b.js:4909
H7	@	index.6894b23b.js:89
r3	@	index.6894b23b.js:89
(anonymous)	@	index.6894b23b.js:89
S	@	index.6894b23b.js:74
R	@	index.6894b23b.js:74
index.6894b23b.js:1113 
 Error executing operator 
Wdn {isRemote: false, pluginName: '@voxel51/operators', _builtIn: true, _config: null}
isRemote
: 
false
pluginName
: 
"@voxel51/operators"
_builtIn
: 
true
_config
: 
null
config
: 
(...)
label
: 
(...)
name
: 
(...)
unlisted
: 
(...)
uri
: 
(...)
[[Prototype]]
: 
Ll
 
MEe {state: Proxy(Object), delegationTarget: undefined, requestDelegation: undefined, params: {…}, _currentContext: {…}, …}
delegationTarget
: 
undefined
executor
: 
null
hooks
: 
{refetchableSavedViews: Array(2), setView: ƒ, setViewName: ƒ}
params
: 
{view: Array(1)}
requestDelegation
: 
undefined
state
: 
Proxy(Object) {set: ƒ, reset: ƒ, refresh: ƒ, gotoSnapshot: ƒ, transact_UNSTABLE: ƒ, …}
_currentContext
: 
{datasetName: 'augm_test', view: Array(0), extended: {…}, filters: {…}, selectedSamples: Set(1), …}
[[Prototype]]
: 
Object
(anonymous)	@	index.6894b23b.js:1113
await in (anonymous) (async)		
(anonymous)	@	index.6894b23b.js:318
(anonymous)	@	index.6894b23b.js:318
ube	@	index.6894b23b.js:89
D7t	@	index.6894b23b.js:318
q$e	@	index.6894b23b.js:318
(anonymous)	@	index.6894b23b.js:318
(anonymous)	@	index.6894b23b.js:4909
H7	@	index.6894b23b.js:89
r3	@	index.6894b23b.js:89
(anonymous)	@	index.6894b23b.js:89
S	@	index.6894b23b.js:74
R	@	index.6894b23b.js:74
index.6894b23b.js:1113 
 
Error: Failed to execute operator @voxel51/operators/set_view. See console for details.
    at $kr (index.6894b23b.js:1113:10368)
    at async index.6894b23b.js:1113:25080
(anonymous)	@	index.6894b23b.js:1113
await in (anonymous) (async)		
(anonymous)	@	index.6894b23b.js:318
(anonymous)	@	index.6894b23b.js:318
ube	@	index.6894b23b.js:89
D7t	@	index.6894b23b.js:318
q$e	@	index.6894b23b.js:318
(anonymous)	@	index.6894b23b.js:318
(anonymous)	@	index.6894b23b.js:4909
H7	@	index.6894b23b.js:89
r3	@	index.6894b23b.js:89
(anonymous)	@	index.6894b23b.js:89
S	@	index.6894b23b.js:74
R	@	index.6894b23b.js:74

**Comment by jacobmarks** [comment]
Hey @iza611 , so I'm pretty sure this is an issue with `set_view()`, which was resolved in FiftyOne version `0.23.8`. Try upgrading and let me know if the issues persists. Marking this as closed for now, but feel free to reopen if you still have trouble.

**Comment by iza611** [comment]
I updated FiftyOne to v0.24.1 and it helped with that error that I was getting when running the 'View last Albumentations run' command :) 

unfortunately, I am still getting this: 
<img width="1073" alt="Zrzut ekranu 2024-06-24 121522" src="https://github.com/voxel51/fiftyone-plugins/assets/57008248/5bc9da72-1d92-4ae9-b79f-e5fb259ccae8">

And when opened each img displays message 'This image failed to load. The file may not exist, or its type (image/jpeg) may be unsupported.'

Do you have any suggestions on how I could deal with this problem? Maybe I can investigate it somewhere in this temporary directory that gets created

**Comment by jacobmarks** [comment]
hmm it looks like the errors you're getting now are implying that the images aren't being created in the temporary directory.

Here is where the image filepaths are defined: https://github.com/jacobmarks/fiftyone-albumentations-plugin/blob/fab86bcec4a95c004207bf7eb6daaeb94167f660/__init__.py#L331

What operating system are you using? Does your computer have a `/tmp/` dir?

**Comment by iza611** [comment]
I'm using Windows 11 pro. I searched my pc for all tmp directories but I don't see any that would be related to fiftyone.

Where exactly should it be created? Should it be in the .fiftyone or the fiftyone folder inside the dir C:/Users/X/?

**Comment by jacobmarks** [comment]
Hey @iza611 , okay I think the issue was the temporary directory locations on windows. I work on mac so I wasn't aware of this difference. Can you try upgrading to the latest version of the plugin and see if it works now?

**Comment by iza611** [comment]
Yes, it works now! It is creating tmp files inside C:/Users/X/AppData/Local/Temp/ directory and I'm not getting the error anymore. Thank you @jacobmarks :)

**Comment by jacobmarks** [comment]
Awesome! So glad it works @iza611  :)
