### ISSUE TITLE
Plugins approval (tile, timestamps)

### ISSUE THREAD

**Issue by mmoollllee** [voxel51/fiftyone-plugins#162]
Hey!

I created two plugins for my use case. Currently without GUI. I'm a novice in all of this, so I'm unsure if I should add those plugins here or not.
I'd be happy if someone would like to check them out and provide feedback :)

[fiftyone-tile](https://github.com/mmoollllee/fiftyone-tile)
[fiftyone-timestamps](https://github.com/mmoollllee/fiftyone-timestamps)

**Comment by brimoor** [comment]
Hi @mmoollllee, these plugins look great! 🙌 

You're welcome to submit a PR to add these plugins to the [Community Plugins section of the README](https://github.com/voxel51/fiftyone-plugins/blob/336c5409d81a2a65631d071bd2924cd30b791381/README.md?plain=1#L141). We'll happily approve it 😄 

Here's an example PR where someone recently did it: https://github.com/voxel51/fiftyone-plugins/pull/157

**Comment by mmoollllee** [comment]
Thank you for the kind feedback and the merge 🙏 
I think I added another interesting feature yesterday. Tiling repeats its process with random tile positions _n_ times and picks the run with the least tiled detections.
I'd be happy to get some feedback!
