### ISSUE TITLE
resolve_placement(self, ctx) in __init__.py

### ISSUE THREAD

**Issue by AliCanibek** [voxel51/fiftyone-plugins#39]
In resolve_placement(..) calling fiftyone.operators.types.Placement(..) with incorrect types
- fiftyone.operators.types.Placement(..) expects param1=place, param2=view but is called wth param1=place, param2=button
Is here an error? should Placement __init__ not be expecting place and button?

**Comment by Sa-Schmi** [comment]
Should be legit because the Button-class inherits from the View-class.
